#!/usr/bin/env python3
"""Generate pyright type stubs for the framework REPL's runtime tool aliases.

The tool REPL (``tool_repl.py``) builds its IPython namespace at *runtime*:
``build_ipython_namespace(manifests)`` mints one ``async def`` wrapper per
discovered tool, keyed by short alias.  Static analysis can't see those names —
they don't exist until discovery scans the repo.  This script closes that gap
for the editor lane:

  1. Run the same no-ChromaDB discovery the REPL itself uses
     (``tool_repl.discover_tools`` — static AST + dynamic import, zero ChromaDB).
  2. Feed the manifests through ``tool_repl.build_tool_aliases`` VERBATIM — the
     alias map this emits is the same one that executes inside the REPL.
     Reimplementing alias logic here would guarantee drift.
  3. Emit two files into a fixed dir outside the repo:

       ~/.local/share/framework-stubs/framework_tools.py
           PEP 562 shim: ``__getattr__`` resolves each alias from the live
           IPython user_ns at access time.  ``__all__`` lists every alias so
           ``from framework_tools import *`` getattr's each entry, triggering
           ``__getattr__`` — which inside the REPL returns the live async wrapper.

       ~/.local/share/framework-stubs/framework_tools.pyi
           One ``async def <alias>(...params...) -> Any: ...`` per alias, built
           from ``_build_signature`` (the exact signature objects the wrappers
           advertise) with ``_build_docstring`` output.  This is what pyright
           consumes for completion + hover + signature help.

Everything here reads framework code — nothing is written back into the repo.

Usage:
    python scripts/gen_repl_stubs.py            # regenerate stubs
    python scripts/gen_repl_stubs.py --check    # exit 1 if stubs are stale

Env knobs:
    FRAMEWORK_STUBS_DIR   override the output dir (default
                          ~/.local/share/framework-stubs)
"""

from __future__ import annotations

import argparse
import inspect
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

# ── Import the framework exactly the way tool_repl.py does ──────────────────
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import tool_repl  # noqa: E402  (after sys.path setup)

OUT_DIR = Path(
    os.environ.get(
        "FRAMEWORK_STUBS_DIR",
        str(Path.home() / ".local/share/framework-stubs"),
    )
)
PY_FILE = OUT_DIR / "framework_tools.py"
PYI_FILE = OUT_DIR / "framework_tools.pyi"

# Permissive catch-all: runtime wrappers accept **kwargs (unknown kwargs go
# through preflight validation and get rejected there), and discovery
# occasionally surfaces params the static schema pass misses.  **kwargs keeps
# the stubs honest against every dispatch path.  Dropping it later is a free
# tightening — static arg-name checking without call-site churn.
_PERMISSIVE = "**kwargs: Any"

_HEADER_STAMP = (
    "Generated by scripts/gen_repl_stubs.py — DO NOT EDIT by hand; "
    "re-run the generator after framework changes."
)


# ── Signature rendering ──────────────────────────────────────────────────────

def _param_str(p: inspect.Parameter) -> str:
    """Render one Parameter as pyright-friendly stub text (ann as string)."""
    ann = "Any"
    if p.annotation is not inspect.Parameter.empty:
        ann = getattr(p.annotation, "__name__", None) or str(p.annotation)
        # Annotation objects render like <class 'str'>; __name__ gives 'str'.
        if ann.startswith("<class"):
            ann = "Any"
    default = ""
    if p.default is not inspect.Parameter.empty:
        default = " = None"
    return f"{p.name}: {ann}{default}"


def _render_signature(manifest) -> str:
    """Render ``(params, **kwargs: Any)`` from the manifest — never re-derived."""
    sig = tool_repl._build_signature(manifest)
    parts = [_param_str(p) for p in sig.parameters.values()]
    has_star = any(
        p.kind in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD)
        for p in sig.parameters.values()
    )
    if not has_star:
        parts.append(_PERMISSIVE)
    return ", ".join(parts)


# ── Stub generation ──────────────────────────────────────────────────────────

def generate_pyi(alias_map: Dict[str, Any]) -> str:
    """Render the full .pyi text for one alias map."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    n = len(alias_map)
    header = [
        '"""Type declarations for the framework tool REPL (runtime-injected aliases).',
        "",
        f"{_HEADER_STAMP}",
        "",
        f"Generated: {now}",
        f"Tool count: {n}",
        "",
        "These are the same names the REPL injects into its IPython user_ns.",
        "Signatures + docstrings come verbatim from tool_repl._build_signature /",
        "_build_docstring on the live discovery manifests — not re-derived,",
        "so editor-side stubs cannot drift from what actually executes.",
        "",
        "Hover (K in nvim) shows each wrapper's manifest-backed docstring.",
        '"""',
        "",
        "from typing import Any",
        "",
    ]

    body: list[str] = []
    for alias in sorted(alias_map):
        m = alias_map[alias]
        sig = _render_signature(m)
        body.append(f"async def {alias}({sig}) -> Any:")
        body.append("    \"\"\"")
        for ln in tool_repl._build_docstring(m).splitlines():
            body.append(f"    {ln}" if ln.strip() else "")
        body.append("    \"\"\"")
        body.append("    ...")
        # One-line tag / handle-kinds comment for quick visual grep.
        tags = getattr(m, "tags", ()) or ()
        handles = getattr(m, "accepted_handle_kinds", ()) or ()
        meta = []
        if handles:
            meta.append("handles: " + ", ".join(handles))
        if tags:
            meta.append("tags: " + ", ".join(tags))
        if meta:
            body.append("    # " + " | ".join(meta))

    return "\n".join(header) + "\n" + "\n".join(body) + "\n"


def build_shim(aliases) -> str:
    """Return the framework_tools.py shim text (PEP 562)."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    n = len(aliases)
    body = "\n".join("    " + repr(a) + "," for a in sorted(aliases))
    return f'''"""PEP 562 shim — runtime-resolved framework tool aliases.

{_HEADER_STAMP}
Generated: {now} | Tools: {n}

Inside the framework REPL (tool_repl.py → the ``ipython`` command), the shell
injects one async wrapper per discovered tool directly into ``user_ns``.  This
shim surfaces those live objects to plain imports:

    from framework_tools import *   # inside the REPL: binds the live wrappers

``__all__`` covers every alias the REPL registers.  Star-import getattr's each
``__all__`` entry, which triggers ``__getattr__``, which pulls the alias from
the live shell (``get_ipython`` is a builtin inside IPython).  The aliases
ALREADY exist in user_ns — this shim costs nothing at REPL time and exists for
the header import in scratch cells.  Outside a live shell attribute access
raises a descriptive AttributeError (never a silent None).
"""

import builtins
from typing import Any

__all__ = [
{body}
]


def __getattr__(name: str) -> Any:
    """PEP 562: resolve ``name`` from the live IPython user_ns at access time."""
    _get_ip = getattr(builtins, "get_ipython", None)
    _ip = _get_ip() if _get_ip else None
    if _ip is not None and name in _ip.user_ns:
        return _ip.user_ns[name]
    raise AttributeError(
        "module 'framework_tools' has no attribute "
        f"{{name!r}}; inside the framework REPL this name should exist in "
        "get_ipython().user_ns — re-run scripts/gen_repl_stubs.py if the "
        "alias list changed."
    )
'''


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate pyright stubs for the REPL's runtime tool aliases."
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if current stubs are stale vs. the live discovery",
    )
    args = ap.parse_args()

    manifests = tool_repl.discover_tools()
    alias_map = tool_repl.build_tool_aliases(manifests)
    aliases = sorted(alias_map)

    pyi_text = generate_pyi(alias_map)
    shim_text = build_shim(aliases)

    if args.check:
        existing_ok = (
            PYI_FILE.exists()
            and PY_FILE.exists()
            and PYI_FILE.read_text() == pyi_text
            and PY_FILE.read_text() == shim_text
        )
        state = "OK" if existing_ok else "STALE"
        print(f"  {state}  {len(aliases)} tools, {PYI_FILE}")
        return 0 if existing_ok else 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    PY_FILE.write_text(shim_text)
    PYI_FILE.write_text(pyi_text)
    print(f"  Wrote {PYI_FILE} ({len(aliases)} tools)")
    print(f"  Wrote {PY_FILE} (PEP 562 shim, __all__ = {len(aliases)} aliases)")
    print(f"  nvim pyright extraPaths → {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
